name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Vitest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: npm run build

      - name: Run tests with coverage
        env:
          MONGODB_URL: ${{secrets.MONGODB_URL}}
          COOKIE_SECRET: ${{secrets.COOKIE_SECRET}}
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
          REDIRECT_URI: ${{secrets.REDIRECT_URI}}
          GITHUB_CLIENT_ID: ${{secrets.GITHUBAUTH_CLIENT_ID}}
          GITHUB_CLIENT_SECRET: ${{secrets.GITHUBAUTH_CALLBACK_URL}}
          GITHUB_CALLBACK_URL: ${{secrets.GITHUBAUTH_CALLBACK_URL}}
        run: npm run test
